config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  get 'home/about'
  get 'home/search'
  post "/home/search" => 'home#search'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @search_crypto = JSON.parse(@response)
    @profit_loss = 0
  end

  def show
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  def new
    @crypto = Crypto.new
  end

  def edit

  end

  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
    if @crypto.save
      format.html { redirect_to @crypto, notice: 'Crypto was successfully saved'}
      format.json { render :show, status: :ok, location: @crypto }
    else
      format.html { render :edit }
      format.json { render json: @crypto.errors, status: :unprocessable_entity }
    end
    end
  end

  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private

  def set_crypto
    @crypto = Crypto.find(params[:id])
  end

  def crypto_params
    params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_purchased )
  end

  def correct_user
    @correct = current_user.cryptos.find_by(id: params[:id])
    redirect_to cryptos_path, notice: "Hey! Not Authorized to edit this entry" if @correct.nil?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # require 'net/http'
    # require 'json'
    #
    # @url = 'https://api.coinmarketcap.com/v1/ticker/'
    # @url = URI(@url)
    # @response = Net::HTTP.get(@url)
    # @coins = JSON.parse(@response)
  end

  def about
  end

  def search
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @url = URI(@url)
    @response = Net::HTTP.get(@url)
    @coin_search = JSON.parse(@response)

   @name = params[:crypto_name]
    if @name
      @name = @name.titlecase
    end

    if @name == ""
      @name = "Please Enter a cryptocurrency name"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_for(@crypto) do |f| %>
  <% if @crypto.errors.any? %>
    <div id="error-explaination">
      <h2><%= pluralize(@crypto.errors.count, "error")%></h2>

    <ul>
      <%= @crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :symbol %><br/>
      <%= f.text_field :symbol %>
    </div>

    <div class="form-group">
      <%= f.number_field :user_id, value: current_user.id, type: "hidden"%>
    </div>

    <div class="form-group">
      <%= f.label :cost_per %><br/>
      <%= f.text_field :cost_per %>
    </div>

    <div class="form-group">
      <%= f.label :amount_purchased %><br/>
      <%= f.text_field :amount_purchased %>
    </div>
    <div class="action">
      <%= f.submit %>
    </div>
  <% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form' %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>
<%= link_to 'Delete Crypto Currency', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/cryptos/index.html.erb
<h1>Crypto Listings</h1>
<br/>
<br/>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Rank</th>
      <th>Current Price</th>
      <th>Total Value</th>
      <th>Profit/Loss</th>
      <th>Cost At Purchase</th>
      <th>Amount Purchased</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
      <tr>
        <% for x in @search_crypto %>
          <% if crypto.symbol == x["symbol"] %>
            <td><%= link_to x["name"], crypto %></td>
            <td><%= x["symbol"]%></td>
            <td><%= x["rank"]%></td>
            <td><%= number_to_currency(x["price_usd"]) %></td>
            <td><%= x["price_usd"].to_d * crypto.amount_purchased %></td>
            <td>$<%= (x["price_usd"].to_d * crypto.amount_purchased) - (crypto.cost_per * crypto.amount_purchased)  %></td>
            <% @profit_loss += (x["price_usd"].to_d * crypto.amount_purchased) - (crypto.cost_per * crypto.amount_purchased)  %>

      <% end %>
      <% end %>

      <td><%= number_to_currency(crypto.cost_per) %></td>
      <td><%= crypto.amount_purchased %></td>
        <td><%= link_to 'Edit', edit_crypto_path(crypto [:id]) %></td>
    </tr>
   <% end %>
  <% end %>

  </tbody>
</table>

<%= link_to "Add new", new_crypto_path, class: "btn btn-primary" %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form' %>

<%= link_to 'back', cryptos_path %>

app/views/cryptos/show.html.erb
<% for x in @show_crypto %>
  <% if @crypto.symbol.upcase == x["symbol"] %>

    <% crypto_name = x["name"] %>
    <% crypto_price = x["price_usd"] %>
    <% crypto_rank = x["rank"] %>
  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= crypto_name %></h3>
  </div>
  <div class="panel-body">

    <h1><%= @crypto.symbol.upcase %></h1>

    <br/><br/>

    <p>
      <strong>Current Price: </strong> <%= number_to_currency(crypto_price) %>
    </p>

    <p>
      <strong>Rank: </strong> <%= crypto_rank %>
    </p>

    <p>
      <strong>Cost per:</strong>
      <%= @crypto.cost_per %>
    </p>

    <p>
      <strong>Amount owned:</strong>
      <%= @crypto.amount_purchased %>
    </p>


  </div>
  <div class="panel-footer">
    <%= link_to 'Edit', edit_crypto_path(@crypto) %> |
    <%= link_to 'Delete Crypto Currency', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', cryptos_path %>
  </div>
</div>

app/views/home/_flash.html.erb
<%= flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissable">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navlinks.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Wallet", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "about", home_about_path %></li>
        <li><%= link_to "search", home_search_path %></li>


        <% if user_signed_in? %>
          <li><%= link_to "list cryptos", cryptos_path %></li>
          <li><%= link_to "add new", new_crypto_path %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "edit profile", edit_user_registration_path %></li>
        <% else %>

          <li><%= link_to "sign up", new_user_registration_path %></li>
          <li><%= link_to "login", user_session_path %></li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>ABOUT</h1>

app/views/home/index.html.erb
<h1>HOME</h1>


<br /><br/>

<%= @coins %>

app/views/home/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Coin Lookup</h3>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <%= form_tag home_search_path, :method => 'POST' do %>
        <%= text_field_tag 'crypto_name', nil, placeholder: 'Enter Crypto Name', size: 50 %>
        <%= submit_tag 'Lookup Crypto' %>
      <% end %>
    </div>
  </div>
</div>

<br/><br/>

<% if @name %>
  <% for x in @coin_search %>
    <% if @name == x["name"] %>
      <%= x["name"] %> <br/><br/>
      Rank: <%= x["rank"] %> <br/><br/>
      <%= x["symbol"] %>: $<%= x["price_usd"] %><br/>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Wallet Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <%= render 'home/navlinks' %>

    <div class="container">


      <%= yield %>
    </div>

  </body>
</html>